#!/bin/bash

. $PREFIX/glibc/opt/termux-style/termux-style
. $PREFIX/glibc/opt/scripts/dialogs
. $PREFIX/glibc/opt/scripts/configs
apply-termux-style

## TODO: Remove this
mkdir -p "$PREFIX/glibc/opt/notice"
if [ ! -e "$PREFIX/glibc/opt/notice/notice1_shown" ]; then
	touch "$PREFIX/glibc/opt/notice/notice1_shown"
	dialog_msgbox "Notice from olegos2" \
		"May 2\nAll Mobox Edge related posts (until now) were not signed off by me. All the information in these posts is not official and is not verified. Mobox Edge has not been announced yet. It doesn't exist yet."
fi
##


while true; do
load_configs
if [ "$WINEESYNC" = "1" ] && [ "$WINEESYNC_TERMUX" = "0" ]; then
	su -c setenforce 0 &>/dev/null
	sudo mkdir /dev/shm &>/dev/null
	sudo chmod 1777 /dev/shm &>/dev/null
fi
dialog_menu "Mobox (wow64)" "" \
"1" "Start Wine" \
"2" "Settings" \
"3" "Manage packages" \
"4" "Select current wine container" \
"5" "Change box64 build" \
"6" "Patch notes (readme)" \
"7" "Updater"
case $? in
1)
	if [ ! "$WINE_PATH" = "" ] && [ -e "$WINE_PATH" ]; then
		chmod 777 $PREFIX/glibc/opt/scripts/start-tfm
		$PREFIX/glibc/opt/scripts/start-tfm
	else
		echo "Selected wine ($(basename $WINE_PATH)) is not installed"
		sleep 3
	fi
;;
2)
	. $PREFIX/glibc/opt/scripts/settings
;;
3)
	load_package-manager
	if [ "$?" = "1" ]; then
		continue
	fi
	defitem_settings=1

	while true; do
	load_configs
	dialog_menu_item $defitem_settings "Install" "" \
	"1" "Verify integrity of local files" \
	"2" "Install wine" \
	"3" "Uninstall wine"
	defitem_settings=$?
	case $defitem_settings in
	1)
		validate-all
		sleep 2
	;;
	2)
		echo ""
		echo -e "\033[1;97mCurrent wine selected:\033[0m $(basename $WINE_PATH)"
		echo ""
		echo -e "\033[1;97mCan be installed:\033[0m"
		
		j=1
		a=()
		for i in "${wine_packages[@]}"; do
		if [ ! -e "$PREFIX/glibc/$i" ]; then
			echo -e "\033[1;32m$j\033[0m) $i"
			j=$((j+1))
			a+=("$i")
		fi
		done
		echo ""
		echo -en "\033[1;97mSelected number:\033[0m \033[1;33m"
		read i
		echo -e "\033[0m"
		re='^[0-9]+$'
		if [[ $i =~ $re ]] && (( 1 <= $i )) && (( $i <= ${#a[@]} )); then
			i=${a[$i-1]}
			sync-package $i
		fi
	;;
	3)
		echo ""
		echo -e "\033[1;97mCurrent wine selected:\033[0m $(basename $WINE_PATH)"
		echo ""
		echo -e "\033[1;97mCan be uninstalled:\033[0m"
		
		j=1
		a=()
		for i in "${wine_packages[@]}"; do
		if [ -e "$PREFIX/glibc/$i" ]; then
			echo -e "\033[1;32m$j\033[0m) $i"
			j=$((j+1))
			a+=("$i")
		fi
		done
		echo ""
		echo -en "\033[1;97mSelected number:\033[0m \033[1;33m"
		read i
		echo -e "\033[0m"
		re='^[0-9]+$'
		if [[ $i =~ $re ]] && (( 1 <= $i )) && (( $i <= ${#a[@]} )); then
			i=${a[$i-1]}
			remove-package $i
		fi
	;;
	255)
		break
	;;
	esac
	done
;;
4)
	echo ""
	echo -e "\033[1;97mCurrent wine selected:\033[0m $(basename $WINE_PATH)"
	echo ""
	echo -e "\033[1;97mInstalled:\033[0m"
	
	j=1
	a=()
	for i in "${wine_packages[@]}"; do
		if [ -e "$PREFIX/glibc/$i" ]; then
			echo -e "\033[1;32m$j\033[0m) $i"
			j=$((j+1))
			a+=("$i")
		fi
	done
	echo ""
	echo -en "\033[1;97mSelected number:\033[0m \033[1;33m"
	read i
	echo -e "\033[0m"
	re='^[0-9]+$'
	if [[ $i =~ $re ]] && (( 1 <= $i )) && (( $i <= ${#a[@]} )); then
		i=${a[$i-1]}
		echo "export WINE_PATH=\$PREFIX/glibc/$i
export WINEPREFIX=\$PREFIX/glibc/$i/.wine">$PREFIX/glibc/opt/conf/wine_path.conf
	fi
	sleep 1
;;
5)
	dialog_menu "Change box64 build" "" \
	"1" "Mar 3 builds" \
	"2" "Feb 14 builds" \
	"3" "Ags 08 builds"
	case $? in
		1)
			tar -xf $PREFIX/glibc/opt/box/mar3.tar.xz -C $PREFIX/glibc/bin
			;;
		2)
			tar -xf $PREFIX/glibc/opt/box/feb14.tar.xz -C $PREFIX/glibc/bin
			;;
		3)
			wget https://github.com/khisy/Moboxmod/releases/download/Moboxmod/box64.tar.xz
			tar -xvf box64.tar.xz -C $PREFIX/glibc/bin/
			rm -rf box64.tar.xz
			;;

	esac
;;
6)
	dialog_msgbox "Patch notes" "\Z3Mar 3\Zn
Updated box64, box64rc, dxvk.conf, locale.conf, path.conf
Added en-ru-locale package that fixes unicode issues in wine
Locale is set to en_US.utf8 by default
Wine is 9.3 by default
Added turnip v6.5, it's default now, no flickering, no mem leaks
Removed turnip v5.5 and v6
Fixed some games that needed nouboopt debug option
Added feb 14 box64
Updated glibc to 2.39
Fixed GTA V memory leak
"
;;
7)
	dialog_menu "Mod Updater" "" \
	"1" "Install new Turnip" \
	"2" "Install new DXVK" \
	"3" "Install MangoHud" \
	"4" "Install new Wine" \
	"5" "Backup" 
	case $? in
	1)
		wget https://github.com/khisy/Moboxmod/releases/download/Moboxmod/turnip.tar.xz
		tar -xf turnip.tar.xz -C $PREFIX/glibc/lib/
		tar xf turnip.tar.xz
		7z a turnip-v5.7z libvulkan_freedreno.so
		mv -f turnip-v5.7z $PREFIX/glibc/opt/libs/mesa/turnip-v5.7z
		rm -rf libvulkan_freedreno.so turnip.tar.xz
		;;
	2)
		wget https://github.com/khisy/Moboxmod/releases/download/Moboxmod/dxvk.tar.gz
		tar xf dxvk.tar.gz
		cd dxvk-2.4
		mv x64 system32
		mv x32 syswow64
		7z a dxvk-0.96.7z sys*
		mv -f dxvk-0.96.7z $PREFIX/glibc/opt/libs/d3d/dxvk-0.96.7z
		cd ..
		rm -rf dxvk-2.4 dxvk.tar.gz
		;;
	3)
		apt update -y
		apt install -y glibc-repo
		apt install -y mangohud-glibc
		echo "export MANGOHUD=1
export MANGOHUD_CONFIG=engine_version,ram,vulkan_driver,wine,gpu_name,horizontal,alpha=0.5" >> $PREFIX/glibc/opt/conf/hud.conf
		;;
	4)
		wget https://github.com/khisy/Moboxmod/releases/download/Moboxmod/wine.tar.xz
		mkdir wine
		tar xf wine.tar.xz -C wine
		mv wine/* wine/wine-9.3-vanilla-wow64
		rm -rf $PREFIX/glibc/wine-9.3-vanilla-wow64
		mv wine/wine-9.3-vanilla-wow64 $PREFIX/glibc/wine-9.3-vanilla-wow64
		rm -rf wine
		;;
	5)
		rm -rf $HOME/Backups
		cd
		mkdir $HOME/Backups
		cp $PREFIX/glibc/opt/libs/mesa/turnip-v5.7z $HOME/Backups
		cp $PREFIX/glibc/opt/libs/d3d/dxvk-0.96.7z $HOME/Backups
		cp $PREFIX/glibc/wine-9.3-vanilla-wow64 ~/backups/wine-9.3-vanilla-wow64
		;;
		esac
;;
255)
	break
;;
esac
done
restore-termux-style
